CREATE OR REPLACE TABLE SNOWFLAKE_LEARNING_DB.CURATED.ORDERS (
    ORDER_ID    NUMBER PRIMARY KEY,
    CUSTOMER_ID NUMBER,
    ORDER_DATE  DATE,
    AMOUNT      NUMBER(10,2),
    CREATED_AT  TIMESTAMP_NTZ,
    UPDATED_AT  TIMESTAMP_NTZ
);