CREATE OR REPLACE TABLE SNOWFLAKE_LEARNING_DB.CURATED.PRODUCTS (
    PRODUCT_ID  NUMBER PRIMARY KEY,
    PRODUCT_NAME STRING,
    CATEGORY    STRING,
    PRICE       NUMBER(10,2),
    CREATED_AT  TIMESTAMP_NTZ,
    UPDATED_AT  TIMESTAMP_NTZ
);