CREATE OR REPLACE TABLE SNOWFLAKE_LEARNING_DB.RAW.ORDER_STG (
    OP          STRING,
    OP_TS       TIMESTAMP_NTZ,
    ORDER_ID    NUMBER,
    CUSTOMER_ID NUMBER,
    ORDER_DATE  DATE,
    AMOUNT      NUMBER(10,2)
);