CREATE OR REPLACE TABLE SNOWFLAKE_LEARNING_DB.RAW.PRODUCT_STG (
    OP          STRING,
    OP_TS       TIMESTAMP_NTZ,
    PRODUCT_ID  NUMBER,
    PRODUCT_NAME STRING,
    CATEGORY    STRING,
    PRICE       NUMBER(10,2)
);