--Create MERGE task in RAW schema
CREATE OR REPLACE TASK SNOWFLAKE_LEARNING_DB.RAW.MERGE_PRODUCT_TASK
WAREHOUSE = COMPUTE_WH
AFTER SNOWFLAKE_LEARNING_DB.RAW.TASK_LOAD_PRODUCT_RAW
AS
MERGE INTO SNOWFLAKE_LEARNING_DB.CURATED.PRODUCTS tgt
USING SNOWFLAKE_LEARNING_DB.RAW.PRODUCT_STREAM src
ON tgt.PRODUCT_ID = src.PRODUCT_ID

WHEN MATCHED AND src.OP = 'U' THEN
UPDATE SET
    PRODUCT_NAME = src.PRODUCT_NAME,
    CATEGORY     = src.CATEGORY,
    PRICE        = src.PRICE,
    UPDATED_AT   = CURRENT_TIMESTAMP

WHEN MATCHED AND src.OP = 'D' THEN
DELETE

WHEN NOT MATCHED AND src.OP = 'I' THEN
INSERT (
    PRODUCT_ID,
    PRODUCT_NAME,
    CATEGORY,
    PRICE,
    CREATED_AT,
    UPDATED_AT
)
VALUES (
    src.PRODUCT_ID,
    src.PRODUCT_NAME,
    src.CATEGORY,
    src.PRICE,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
);

--Attach predecessor
ALTER TASK SNOWFLAKE_LEARNING_DB.RAW.MERGE_PRODUCT_TASK
ADD AFTER SNOWFLAKE_LEARNING_DB.RAW.TASK_LOAD_PRODUCT_RAW;