--Create MERGE task in RAW schema
CREATE OR REPLACE TASK SNOWFLAKE_LEARNING_DB.RAW.MERGE_CUSTOMER_TASK
WAREHOUSE = COMPUTE_WH
AS
MERGE INTO SNOWFLAKE_LEARNING_DB.CURATED.CUSTOMER tgt
USING SNOWFLAKE_LEARNING_DB.RAW.CUSTOMER_STG_STREAM src
ON tgt.CUSTOMER_ID = src.CUSTOMER_ID

WHEN MATCHED AND src.OP = 'D' THEN
    DELETE

WHEN MATCHED AND src.OP = 'U' THEN
    UPDATE SET
        tgt.FIRST_NAME = src.FIRST_NAME,
        tgt.LAST_NAME  = src.LAST_NAME

WHEN NOT MATCHED AND src.OP = 'I' THEN
    INSERT (CUSTOMER_ID, FIRST_NAME, LAST_NAME)
    VALUES (src.CUSTOMER_ID, src.FIRST_NAME, src.LAST_NAME);



--Attach predecessor
ALTER TASK SNOWFLAKE_LEARNING_DB.RAW.MERGE_CUSTOMER_TASK
ADD AFTER SNOWFLAKE_LEARNING_DB.RAW.TASK_LOAD_CUSTOMER_RAW;