--Create MERGE task in RAW schema
CREATE OR REPLACE TASK SNOWFLAKE_LEARNING_DB.RAW.MERGE_ORDER_TASK
WAREHOUSE = COMPUTE_WH
AS
MERGE INTO SNOWFLAKE_LEARNING_DB.CURATED.ORDERS tgt
USING SNOWFLAKE_LEARNING_DB.RAW.ORDER_STREAM src
ON tgt.ORDER_ID = src.ORDER_ID

WHEN MATCHED AND src.OP = 'U' THEN
UPDATE SET
    CUSTOMER_ID = src.CUSTOMER_ID,
    ORDER_DATE  = src.ORDER_DATE,
    AMOUNT      = src.AMOUNT,
    UPDATED_AT  = CURRENT_TIMESTAMP

WHEN MATCHED AND src.OP = 'D' THEN
DELETE

WHEN NOT MATCHED AND src.OP = 'I' THEN
INSERT (
    ORDER_ID,
    CUSTOMER_ID,
    ORDER_DATE,
    AMOUNT,
    CREATED_AT,
    UPDATED_AT
)
VALUES (
    src.ORDER_ID,
    src.CUSTOMER_ID,
    src.ORDER_DATE,
    src.AMOUNT,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
);


--Attach predecessor
ALTER TASK SNOWFLAKE_LEARNING_DB.RAW.MERGE_ORDER_TASK
ADD AFTER SNOWFLAKE_LEARNING_DB.RAW.TASK_LOAD_ORDER_RAW;