CREATE OR REPLACE TASK SNOWFLAKE_LEARNING_DB.RAW.TASK_LOAD_PRODUCT_RAW
  WAREHOUSE = COMPUTE_WH
  SCHEDULE = '2 MINUTE'
AS
COPY INTO SNOWFLAKE_LEARNING_DB.RAW.PRODUCT_STG
FROM @SNOWFLAKE_LEARNING_DB.RAW.AARTHI_S3_STAGE/product
FILE_FORMAT = (FORMAT_NAME = SNOWFLAKE_LEARNING_DB.RAW.AARTHI_CSV_FORMAT);