CREATE OR REPLACE FILE FORMAT SNOWFLAKE_LEARNING_DB.RAW.AARTHI_CSV_FORMAT
TYPE = 'CSV'
FIELD_DELIMITER = ','
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
NULL_IF = ('', 'NULL')
TRIM_SPACE = TRUE
TIMESTAMP_FORMAT = 'YYYY-MM-DD HH24:MI:SS';