CREATE OR REPLACE STAGE SNOWFLAKE_LEARNING_DB.RAW.AARTHI_S3_STAGE
URL = 's3://aarthi-snowflake-project/raw/'
STORAGE_INTEGRATION = AARTHI_S3_INT
FILE_FORMAT = SNOWFLAKE_LEARNING_DB.RAW.AARTHI_CSV_FORMAT;