CREATE OR REPLACE STORAGE INTEGRATION AARTHI_S3_INT
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = S3
ENABLED = TRUE
STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::993666109269:role/SnowflakeS3Role'
STORAGE_ALLOWED_LOCATIONS = ('s3://aarthi-snowflake-project/raw/');